#! /bin/bash

cd /tmp
wget wget http://cn.php.net/distributions/php-5.4.4.tar.gz

tar zxvf php-5.4.4.tar.gz
cd php-5.4.4

./configure \
--prefix=/opt/php \
--with-config-file-path=/opt/php/etc \
--with-mysql=/opt/mysql/
--with-mysqli=/opt/mysql/bin/mysql_config \
--with-pdo-mysql=/opt/mysql \
--with-iconv-dir=/usr/local \
--enable-fastcgi --enable-fpm
--enable-force-cgi-redirect \
--disable-phar \
--with-fpm-user=www \
--with-fpm-group=www \
--with-pcre-regex \
--enable-xml \
--disable-rpath \
--enable-discard-path \
--enable-safe-mode \
--enable-bcmath \
--enable-shmop \
--enable-sysvsem \
--enable-inline-optimization \
--with-zlib \
--with-bz2 \
--enable-calendar \
--with-curl \
--enable-dba \
--with-libxml-dir \
--with-gd \
--with-jpeg-dir \
--with-png-dir \
--with-zlib-dir \
--with-freetype-dir \
--enable-gd-native-ttf \
--with-openssl \
--with-mhash \
--enable-mbstring \
--with-mcrypt \
--enable-mbregex \
--enable-pcntl \
--enable-xml \
--enable-shmop \
--enable-sockets \
--enable-zip \
--enable-soap
